[workspace]
authors = ["IMJONEZZ <46764336+IMJONEZZ@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "CANCapital"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.11"

[pypi-dependencies]
pandas = ">=2.3.2, <3"
numpy = ">=2.3.2, <3"
matplotlib = ">=3.10.6, <4"
seaborn = ">=0.13.2, <0.14"
scikit-learn = ">=1.7.1, <2"
tqdm = ">=4.67.1, <5"
category-encoders = ">=2.8.1, <3"
gradio = ">=5.49.1, <6"
